# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: LogisticRegressionInHaskell
version: '0.0.0'
github: "githubuser/LogisticRegressionInHaskell"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: LogisticRegressionInHaskell is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  dependencies:
  - base
  source-dirs: library
  exposed-modules:
  - LogisticRegrecion

executables:
  LogisticRegressionInHaskell:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - LogisticRegressionInHaskell
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  LogisticRegressionInHaskell-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - LogisticRegressionInHaskell
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  LogisticRegressionInHaskell-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - LogisticRegressionInHaskell
    - hspec
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
